# Generated by Django 5.1.6 on 2025-05-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_comments'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course'),
        ),
    ]
