# Generated by Django 5.1.6 on 2025-02-24 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('other', 'Other')], default='registration', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'purpose')},
            },
        ),
    ]
