# Generated by Django 5.1.6 on 2025-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fcmtoken_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'token')},
        ),
    ]
