# Generated by Django 5.1.6 on 2025-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('cancel', 'Cancel'), ('locked', 'Locked'), ('refund', 'Refund'), ('purchase', 'Purchase')], max_length=10),
        ),
    ]
