# Generated by Django 5.1.6 on 2025-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
