# Generated by Django 5.1.6 on 2025-03-26 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 16, 13, 21, 66083, tzinfo=datetime.timezone.utc)),
        ),
    ]
