# Generated by Django 5.1.6 on 2025-04-07 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 4, 7, 40, 552839, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
