# Generated by Django 5.1.6 on 2025-04-07 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_is_unlocked_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 6, 18, 25, 957182, tzinfo=datetime.timezone.utc)),
        ),
    ]
