# Generated by Django 5.1.6 on 2025-04-12 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 3, 29, 55, 178880, tzinfo=datetime.timezone.utc)),
        ),
    ]
