# Generated by Django 5.1.6 on 2025-04-20 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 17, 23, 17, 17863, tzinfo=datetime.timezone.utc)),
        ),
    ]
