# Generated by Django 5.1.6 on 2025-04-22 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 5, 2, 6, 546249, tzinfo=datetime.timezone.utc)),
        ),
    ]
