# Generated by Django 5.1.6 on 2025-05-02 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 5, 23, 57, 131581, tzinfo=datetime.timezone.utc)),
        ),
    ]
