# Generated by Django 5.1.6 on 2025-05-03 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='locked_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 32, 4, 101218, tzinfo=datetime.timezone.utc)),
        ),
    ]
